[package]
name = "overlay_segmenter"
version = "0.1.0"
edition = "2024"

[dependencies]

anyhow = "1.0.102"

safetensors = "0.7.0"
image = {version="0.25.10", features=["jpeg"]}
flash_powder = { git = "https://github.com/iwanders/flash_powder.git", version = "0.1.0", features = ["cuda", "v2_13"] }

[build-dependencies]
flash_powder = { git = "https://github.com/iwanders/flash_powder.git", version = "0.1.0" }
